services:
  postgres:
    image: postgres:16
    container_name: healthcare-postgres
    environment:
      POSTGRES_DB: healthcare_pms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - healthcare_postgres_data:/var/lib/postgresql/data

  api:
    build: .
    image: healthcare-api
    container_name: healthcare-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/healthcare_pms
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  healthcare_postgres_data: